port:  5000
markdown: kramdown
name: 2nd City Zoning
title: 2nd City Zoning
url: http://secondcityzoning.org
description: "An interactive map that lets you find out how your building is zoned, learn where to locate your business and explore zoning patterns throughout Chicago."
encoding: utf-8
timezone: America/Chicago
permalink: pretty
navigation:
- text: Home
  url: /
- text: Zoning districts
  url: /zones/
  category: zones
- text: Zoning rules
  url: /zoning_rules/
- text: About
  url: /about/